---
title             : "Acceptability judgments in Colloquial Singaporean English"
shorttitle        : "CSE acceptability"

author: 
  - name          : "Alvin Wei Ming Tan"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    # address       : "Postal address"
    email         : "tanawm@stanford.edu"
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - "Conceptualisation"
      - "Methodology"
      - "Investigation"
      - "Formal analysis"
      - "Visualisation"
      - "Writing - Original draft"
      - "Writing - Review & editing"
  - name          : "Louise Mycock"
    affiliation   : "2"
    role:
      - "Writing - Review & editing"
      - "Supervision"

affiliation:
  - id            : "1"
    institution   : "Stanford University"
  - id            : "2"
    institution   : "University of Oxford"

authornote: |
  Alvin Wei Ming Tan, Department of Psychology, Stanford University, ORCID 0000-0001-5551-7507.
  
  Louise Mycock, Faculty of Linguistics, Philology, and Phonetics, University of Oxford, ORCID 0000-0003-3473-0979.
  
  AWMT conducted this research while at the University of Oxford.
  
  The authors declare no conflicts of interest.

abstract: |
  Colloquial Singaporean English (CSE) includes several optional features which vary in their usage.
  Such features include the zero copula in copular constructions (e.g., "Tom $\emp$ very tall"), as well as the lack of past tense inflection in past constructions (e.g., "Yesterday, she go to the store").
  In this study, we used an acceptability judgement task to estimate the effect of social factors (e.g., mother tongue language) and linguistic factors (e.g., complement type or past inflection form) on CSE speakers' acceptability of these two classes of constructions.
  For copular constructions, we found that PP complements were more acceptable than NP or AP complements with a zero copula, and there were no differences in ratings between Malay and Chinese speakers.
  These results suggest that previously-found differences have been levelled among CSE speakers.
  For past tense constructions, Malay speakers showed a greater difference in ratings than Chinese speakers for sentences with versus without past tense inflection.
  There were also no differences among different forms of past tense inflection (suppletion, vowel change, affixation), contrasting with previous studies.
  These results help to complement and clarify the findings from corpus-based studies of the distribution of these optional features among CSE speakers, demonstrating the utility of using acceptability judgements to study sociolinguistic variation and language change.
  
keywords          : "Colloquial Singaporean English, acceptability judgments, sociolinguistics, variation"
wordcount         : "X"

bibliography      : "references.bib"

floatsintext      : yes
linenumbers       : yes
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

mainfont          : "CMU Serif"

classoption       : "man"
output            : 
  papaja::apa6_pdf:
    latex_engine: xelatex
header-includes   : 
  - \DeclareSymbolFont{AMSb}{U}{msb}{m}{n}
  - \DeclareMathSymbol{\emp}{\mathord}{AMSb}{"3F}
  - \usepackage{xeCJK}
  - \usepackage{linguex}
---

```{r setup, include = FALSE}
library(papaja)
# library(glossr)
library(tidyverse)
library(here)
library(lme4)
library(lmerTest)
library(broom.mixed)
library(redres)
library(emmeans)
library(ggpubr)
library(gt)
library(rstatix)
library(moments)
# use_glossr()
# options("glossr.output" = "latex")
r_refs("r-references.bib")
knitr::opts_knit$set(root.dir = './')
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  error = FALSE,
  echo = FALSE,
  dev = "cairo_pdf")
extrafont::loadfonts()
theme_set(theme_bw())
theme_update(panel.grid = element_blank(),
             strip.background = element_blank(),
             legend.key = element_blank(),
             legend.position = "bottom")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
floor_dec <- function(x, level=1) round(x - 5*10^(-level-1), level)
```

```{r child = "text/01-introduction.Rmd"}
```

```{r child = "text/02-methods.Rmd"}
```

```{r child = "text/03-results.Rmd"}
```

```{r child = "text/04-discussion.Rmd"}
```

\newpage

# References

::: {#refs custom-style="Bibliography"}
:::

\newpage

```{r child = "text/99-appendix.Rmd"}
```

